export const fotos = [
  {
    title: "O início... primeira vez que ficamos!",
    url: "./fotos/0.jpeg",
  },
  { title: "Nosso primeiro passeio.", url: "./fotos/1.jpg" },
  { title: "Meus presentes de dia dos namorados.", url: "./fotos/2.jpg" },
  { title: "E nosso encontro de dia dos namorados!", url: "./fotos/3.jpg" },
  { title: "Nós no seu aniversário.", url: "./fotos/4.jpg" },
  { title: "Aquele açaí de lei", url: "./fotos/5.jpg" },
  { title: "A gente viajando pra Águas de São Pedro.", url: "./fotos/8.jpg" },
  { title: "Chegamos lá e foi incrível!", url: "./fotos/9.jpg" },
  {
    title: "O dia que te pedi em namoro (tava gatona).",
    url: "./fotos/10.jpg",
  },
  {
    title: "Oficialmente namorados! 08/08.",
    url: "./fotos/10-2.jpeg",
  },
  { title: "Amo você.", url: "./fotos/57.jpeg" },
  { title: "Amo seu doguinho.", url: "./fotos/56.jpeg" },
  { title: "Amo sua família.", url: "./fotos/11.jpg" },
  {
    title: "Ainda mais com essa primeira janta da sogra.",
    url: "./fotos/12.jpg",
  },
  { title: "Mas minha namorada cozinha tb!", url: "./fotos/13.jpg" },
  { title: "Vistando Campos do Jordão com você.", url: "./fotos/15.jpg" },
  { title: "Lembra do desejo na fonte? Eu sim!", url: "./fotos/14.jpg" },
  { title: "Outubro foi um mês especial.", url: "./fotos/54.jpeg" },
  { title: "Dia 8 te dei uma aliança.", url: "./fotos/17.jpg" },
  { title: "E comemoramos comendo!", url: "./fotos/16.jpg" },
  { title: "Ainda em outubro fomos ver o Bruninho!", url: "./fotos/18.jpg" },
  { title: "Já em novembro fomos pra Foz...", url: "./fotos/19.jpg" },
  { title: "Você conseguiu ofuscar as cataratas.", url: "./fotos/20.jpg" },
  { title: "Amo essa foto! (Dezembro)", url: "./fotos/22.jpg" },
  { title: "Comemoração do mês foi inesquecível.", url: "./fotos/23.jpg" },
  { title: "Sua primeira árvore de natal montada!", url: "./fotos/24.jpg" },
  { title: "Bem vindo, 2025!", url: "./fotos/27.jpg" },
  { title: "Comemoração de Janeiro.", url: "./fotos/28.jpg" },
  { title: "A Dama e o Vagabundo em Olimpia.", url: "./fotos/29.jpg" },
  { title: "Chaves e Chiquinha S2", url: "./fotos/30.jpg" },
  { title: "Fevereiro foi bom...", url: "./fotos/32.jpg" },
  { title: "Março você mesmo disse que amou kkk", url: "./fotos/33.jpg" },
  { title: "E a gente come muito, olha abril.", url: "./fotos/34.jpg" },
  { title: "Teve o niver da minha vó. Ela ama você.", url: "./fotos/36.jpg" },
  { title: "E a sua sogra também!", url: "./fotos/55.jpeg" },
  { title: "Pra não deixar maio passar batido... PT1", url: "./fotos/37.jpg" },
  { title: "Também viajamos pra Embu!", url: "./fotos/38.jpg" },
  { title: "E conhecemos um café muito charmoso.", url: "./fotos/39.jpg" },
  { title: "Pra não deixar maio passar batido... PT2", url: "./fotos/40.jpg" },
  { title: "Nosso dia/dia dos namorados de 2025.", url: "./fotos/53.jpeg" },
  { title: "Não pode faltar comida kkkk", url: "./fotos/41.jpg" },
  {
    title: "Presente do teatro que nunca vou esquecer!",
    url: "./fotos/51.jpeg",
  },
  { title: "Mais um niver ao seu lado S2", url: "./fotos/52.jpeg" },
  { title: "E de repente chegamos em julho...", url: "./fotos/45.jpg" },
  { title: "Uma viagem pra fechar o mês", url: "./fotos/47.jpg" },
  { title: "Em agosto pude comemorar o meu niver", url: "./fotos/49.jpg" },
  { title: "Com a mulher mais incrível do mundo", url: "./fotos/50.jpg" },
  { title: "Que nunca faltem sonequinhas", url: "./fotos/43.jpg" },
  { title: "Lanches deliciosos", url: "./fotos/44.jpg" },
  { title: "E amor até o fim!", url: "./fotos/48.jpg" },
];
